#!/bin/bash

LEVON=`/sbin/ifconfig | tr -s ' ' | cut -f 1 -d ' ' `
for i in $LEVON
do
echo $i
var=$( /sbin/ifconfig $i | grep HWaddr )
if [  -n "$var"  ]
then
echo "MacAdress:" `/sbin/ifconfig $i | grep  HWaddr | awk ' {print $5}'` 
fi
#echo `/sbin/ifconfig $i | grep "inet addr" `
done
exit 0





